# Generated by Django 4.2.2 on 2023-06-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_description_snack_desc_remove_snack_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
