# Generated by Django 4.2.2 on 2023-06-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_rename_desc_snack_description_alter_snack_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='description',
            new_name='desc',
        ),
    ]
